when:
  - event: push
  - event: tag

steps:
  - name: build
    image: gcc:latest
    commands: # we probably shouldn't install cmake every time
      - apt update && apt install -y cmake
      - mkdir -p build/ && cd build
      - cmake .. --toolchain ../toolchain/sanitize.cmake
      - make
  - name: test
    image: ubuntu
    commands:
      # Automated tests, this should not fail
      - ./build/test
      # Manual test, you can see the output of this in woodpecker
      - echo "(print 42)" | ./build/main
  # TODO: add publish step, when we're at a working state.